spring.application.name=inf1032
server.port=${PORT:8081}
#spring.mongodb.uri=${DATABASE_URL}
spring.mongodb.uri=mongodb+srv://s4ndr4ng:FZhZNTOkqYSqnZ2N@cluster0.igwgvqr.mongodb.net/inf1030?retryWrites=true&w=majority&appName=Cluster0&uuidRepresentation=standard
inf1032.jwt.tokenHeader=Authorization
inf1032.jwt.tokenPrefix=Bearer
inf1032.jwt.secret=mySuperSecret123456
#inf1032.jwt.secret=${INF1032_JWT_SECRET}
inf1032.jwt.tokenExpiration=2
inf1032.jwt.tokenIssuer=inf1032-app